#!/usr/bin/python

import subprocess as sub
import sys, os

dir = sub.Popen(['which', 'decktape'], stdout=sub.PIPE)\
         .communicate()[0]\
         .strip('\n')\
         .replace('//decktape', '/')

args = sys.argv
if len(args)>1:
    cmd = '%s/bin/phantomjs %s/decktape.js '%(dir, dir) + ' '.join(args[1:])
    print cmd
    os.system(cmd)
else:
    print "Please pass arguments to the command"

