#!/usr/bin/python

import subprocess as sub
import sys, os

args = sys.argv
if len(args)>1:
    other = args[1:-2]
    input = args[-2]
    output = args[-1]
    cmd = ('docker run --rm -v `pwd`:`pwd` -w `pwd` astefanutti/decktape ' \
            '%s file://`pwd`/%s `pwd`/%s'\
           %(' '.join(other), input, output))
    print cmd
    os.system(cmd)
else:
    print "Please pass arguments to the command"

